name: CI/CD Pipeline for Next.js App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Check SSH connection
        run: |
          echo "Testing SSH connection to ${{ secrets.SERVER_IP }}"
          nc -zv ${{ secrets.SERVER_IP }} 22

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SERVER_SSH_KEY }}
          known_hosts: unnecessary
          if_key_exists: replace

      - name: Adding Known Hosts
        run: |
          mkdir -p ~/.ssh
          touch ~/.ssh/known_hosts
          ssh-keyscan -H -T 60 ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts 2>/dev/null
          cat ~/.ssh/known_hosts

      - name: Deploy to Ubuntu server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ${{ secrets.DEPLOY_PATH }}

            # Pull the latest changes
            git fetch --all
            git reset --hard origin/main

            # Build and start Docker containers
            docker-compose down
            docker-compose build --no-cache
            docker-compose up -d

            # Clean up old images
            docker image prune -f
